### ISSUE TITLE
Project missing SQL Context.

### ISSUE THREAD

**Issue by tgalazka** [kj07208/Columbia#1]
I am unable to build the solution due to the missing class _HrDbContext_.

This affects the following classes:
- OtpPaymentController
- EmployeeRepository
- HrRepository
- OneTimePaymentRepository
- EmployeeController

**Comment by kj07208** [comment]
Can you please call me at 10:30 today.
I can give you all details.
908-451-3347

**Comment by tgalazka** [comment]
Sounds good; speak to you then.
